version: "2.1"
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "3300:3000/tcp"
      - "80:80/tcp"
    volumes:
       - ${DATADIR}/adguard/workdir:/opt/adguardhome/work
       - ${DATADIR}/adguard/confdir:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
