version: "2.1"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      #- PLEX_CLAIM=${PLEXCLAIMID}
    volumes:
      - ${DATADIR}/plex:/config
      - ${MEDIADIR}:/mnt/media
    restart: unless-stopped
    
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    volumes:
      - ${DATADIR}/tautulli:/config
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8001:8000/tcp # Built-in HTTP control server
      - 6881:6881 # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 8080:8080 # qBittorrent
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
    volumes:
      - /dockerData/gluetun:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
      - VPNSP=${VPNSP}
      - CITY=${CITY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${DATADIR}/qbittorrent:/config
      - ${DOWNLOADSDIR}:/downloads
    restart: unless-stopped
    #ports:
      #- 6881:6881
      #- 6881:6881/udp
      #- 8080:8080
    network_mode: service:gluetun

  prowlarr:
    image: hotio/prowlarr:testing
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/prowlarr:/config
    #ports:
      #- 9696:9696
    restart: unless-stopped
    network_mode: service:gluetun

  radarr:
    image: hotio/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies
      - ${DOWNLOADSDIR}:/downloads
    #ports:
      #- 7878:7878
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/sonarr:/config
      - ${MEDIADIR}/shows:/tv
      - ${DOWNLOADSDIR}:/downloads
    #ports:
      #- 8989:8989
    restart: unless-stopped
    network_mode: service:gluetun
