version: "2.1"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - ${DATADIR}/plex:/config
      #- /path/to/tvseries:/tv
      #- /path/to/movies:/movies
    restart: unless-stopped
    
