version: "2.1"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - ${DATADIR}/plex:/config
      - ${MEDIADIR}:/mnt/media
    restart: unless-stopped
    
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    volumes:
      - ${DATADIR}/tautulli:/config
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment: SERVERURL, SERVERPORT, INTERNAL_SUBNET and PEERDNS
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${DATADIR}/qbittorrent:/config
      - ${DOWNLOADSDIR}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    network_mode: "service:wireguard"

  prowlarr:
    image: hotio/prowlarr:testing
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
