---

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    ports:
      - 8096:8096/tcp
    volumes:
      - ${DATA_DIR}/config/jellyfin-config:/config
      - ${DATA_DIR}/config/jellyfin-cache:/cache
      - ${DATA_DIR}:/data
    environment:
      - TZ=${TIMEZONE}
      - /dev/dri:/dev/dri
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports: # Expose qBittorrent's web UI and torrent ports through VPN
      - 8080:8080     # qBittorrent Web UI
      - 6881:6881     # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 9696:9696     # Prowlarr
      - 8191:8191     # FlareSolverr
      - 7878:7878     # Radarr
      - 8989:8989     # Sonarr
      - 6767:6767     # Bazarr
      # - 8096:8096   # Jellyfin
      # - 5055:5055   # Jellyseerr
    volumes:
      - ${DATA_DIR}/config/gluetun:/gluetun
    environment:
      - TZ=${TIMEZONE}
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
      # - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS} # if you have port forwarding enabled
      # - VPN_PORT_FORWARDING=on # Private Internet Access or ProtonVPN only
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun" # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - WEBUI_ADDRESS=0.0.0.0
      - WEBUI_EXTERNAL_ACCESS=true
    volumes:
      - ${DATA_DIR}/config/qbittorrent:/config
      - ${DATA_DIR}:/data
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #   - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_DIR}/config/prowlarr:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - gluetun
    # ports:
    #   - 8191:8191
    volumes:
      - ${DATA_DIR}/config/flaresolverr:/config
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #   - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_DIR}/config/radarr:/config
      - ${DATA_DIR}:/data

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #   - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_DIR}/config/sonarr:/config
      - ${DATA_DIR}:/data

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr
    init: true
    container_name: jellyseerr
    environment:
      - TZ=${TIMEZONE}
      - LOG_LEVEL=info
    ports:
      - 5055:5055
    volumes:
      - ${DATA_DIR}/config/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      - gluetun
      - jellyfin
      - prowlarr
      - sonarr
      - radarr

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # ports:
    #   - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_DIR}/config/bazarr:/config
      - ${DATA_DIR}:/data

  samba:
    image: ghcr.io/dockur/samba
    container_name: samba
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - NAME=${SMB_SHARE}
      - USER=${SMB_USER}
      - PASS=${SMB_PASS}
    ports:
      - 445:445
    volumes:
      - ${DATA_DIR}:/storage
    restart: unless-stopped
